server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
  max-http-header-size: 32MB

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

spring:
  application:
    name: hr-system
  main:
    allow-bean-definition-overriding: true
  jpa.properties.javax.persistence.validation.mode: none
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hr_system}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:/db/migration
    enabled: true
    out-of-order: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        current_session_context_class: thread